### ISSUE TITLE
Datapoint update takes seconds to complete

### ISSUE THREAD

**Issue by acropup** [vhs/api#9]
It's taking up to 5 seconds for a value update to change the value received upon a query. I don't know enough about this framework to know if this is expected.

To Reproduce:
Prepare two web browser tabs.
1. Update tab: http://api.hackspace.ca/s/vhs/data/test1/update?value=test1
2. Query tab: http://api.hackspace.ca/s/vhs/data/test1.txt

Go to Query tab, and make sure the value is different from the value being submitted in the Update's querystring.
Submit Update query, i.e. go to Update URL.
Immediately switch to Query tab, press F5 repeatedly and watch for change.

Current Behaviour:
The value seems to change within 5 seconds of submitting an update.

Expected Behaviour:
The first query after an update, no matter how soon after, should return the updated value.

@interlock, do you have any idea why this is happening?

**Comment by interlock** [comment]
@acropup I believe this is a side effect of influxdb being used instead of redis now.

My first guess, based on the InfluxDB notes, is that the timestamp being sent for the data point is 5 seconds or so in the future for the InfluxDB instance. InfluxDB will not return a result from the future.. because that is time travel!

@garthomite Is InfluxDB running on the same machine at the api? If not, we probably just need to setup ntp on each to fight the clock drift.

**Comment by garthomite** [comment]
They are running on the same server, I think it takes a second to commit
the result - I noticed this as well.

If it becomes a problem then I might have to cache the last update in
memory which isn't ideal.

**Comment by acropup** [comment]
It's not a significant problem for me, it was just something my unit tests
revealed as I was debugging my program. I don't necessarily need it to
respond immediately, and Garth will be making a new API specifically for
the door anyway.
